create table "public"."testing-table" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now()
);


alter table "public"."testing-table" enable row level security;

CREATE UNIQUE INDEX "testing-table_pkey" ON public."testing-table" USING btree (id);

alter table "public"."testing-table" add constraint "testing-table_pkey" PRIMARY KEY using index "testing-table_pkey";

grant delete on table "public"."testing-table" to "anon";

grant insert on table "public"."testing-table" to "anon";

grant references on table "public"."testing-table" to "anon";

grant select on table "public"."testing-table" to "anon";

grant trigger on table "public"."testing-table" to "anon";

grant truncate on table "public"."testing-table" to "anon";

grant update on table "public"."testing-table" to "anon";

grant delete on table "public"."testing-table" to "authenticated";

grant insert on table "public"."testing-table" to "authenticated";

grant references on table "public"."testing-table" to "authenticated";

grant select on table "public"."testing-table" to "authenticated";

grant trigger on table "public"."testing-table" to "authenticated";

grant truncate on table "public"."testing-table" to "authenticated";

grant update on table "public"."testing-table" to "authenticated";

grant delete on table "public"."testing-table" to "service_role";

grant insert on table "public"."testing-table" to "service_role";

grant references on table "public"."testing-table" to "service_role";

grant select on table "public"."testing-table" to "service_role";

grant trigger on table "public"."testing-table" to "service_role";

grant truncate on table "public"."testing-table" to "service_role";

grant update on table "public"."testing-table" to "service_role";


