create table "public"."testing_table_local" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now()
);


alter table "public"."testing_table_local" enable row level security;

CREATE UNIQUE INDEX testing_table_local_pkey ON public.testing_table_local USING btree (id);

alter table "public"."testing_table_local" add constraint "testing_table_local_pkey" PRIMARY KEY using index "testing_table_local_pkey";

grant delete on table "public"."testing_table_local" to "anon";

grant insert on table "public"."testing_table_local" to "anon";

grant references on table "public"."testing_table_local" to "anon";

grant select on table "public"."testing_table_local" to "anon";

grant trigger on table "public"."testing_table_local" to "anon";

grant truncate on table "public"."testing_table_local" to "anon";

grant update on table "public"."testing_table_local" to "anon";

grant delete on table "public"."testing_table_local" to "authenticated";

grant insert on table "public"."testing_table_local" to "authenticated";

grant references on table "public"."testing_table_local" to "authenticated";

grant select on table "public"."testing_table_local" to "authenticated";

grant trigger on table "public"."testing_table_local" to "authenticated";

grant truncate on table "public"."testing_table_local" to "authenticated";

grant update on table "public"."testing_table_local" to "authenticated";

grant delete on table "public"."testing_table_local" to "service_role";

grant insert on table "public"."testing_table_local" to "service_role";

grant references on table "public"."testing_table_local" to "service_role";

grant select on table "public"."testing_table_local" to "service_role";

grant trigger on table "public"."testing_table_local" to "service_role";

grant truncate on table "public"."testing_table_local" to "service_role";

grant update on table "public"."testing_table_local" to "service_role";


