create table "public"."users_has_products" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "id_product" bigint,
    "id_user" bigint
);


alter table "public"."users_has_products" enable row level security;

CREATE UNIQUE INDEX users_has_products_pkey ON public.users_has_products USING btree (id);

alter table "public"."users_has_products" add constraint "users_has_products_pkey" PRIMARY KEY using index "users_has_products_pkey";

alter table "public"."users_has_products" add constraint "public_users_has_products_id_product_fkey" FOREIGN KEY (id_product) REFERENCES products(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."users_has_products" validate constraint "public_users_has_products_id_product_fkey";

alter table "public"."users_has_products" add constraint "public_users_has_products_id_user_fkey" FOREIGN KEY (id_user) REFERENCES users(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."users_has_products" validate constraint "public_users_has_products_id_user_fkey";

grant delete on table "public"."users_has_products" to "anon";

grant insert on table "public"."users_has_products" to "anon";

grant references on table "public"."users_has_products" to "anon";

grant select on table "public"."users_has_products" to "anon";

grant trigger on table "public"."users_has_products" to "anon";

grant truncate on table "public"."users_has_products" to "anon";

grant update on table "public"."users_has_products" to "anon";

grant delete on table "public"."users_has_products" to "authenticated";

grant insert on table "public"."users_has_products" to "authenticated";

grant references on table "public"."users_has_products" to "authenticated";

grant select on table "public"."users_has_products" to "authenticated";

grant trigger on table "public"."users_has_products" to "authenticated";

grant truncate on table "public"."users_has_products" to "authenticated";

grant update on table "public"."users_has_products" to "authenticated";

grant delete on table "public"."users_has_products" to "service_role";

grant insert on table "public"."users_has_products" to "service_role";

grant references on table "public"."users_has_products" to "service_role";

grant select on table "public"."users_has_products" to "service_role";

grant trigger on table "public"."users_has_products" to "service_role";

grant truncate on table "public"."users_has_products" to "service_role";

grant update on table "public"."users_has_products" to "service_role";


