name: Deployment Supabase

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - main
      - dev
  workflow_dispatch:

jobs:
  migrate:
    runs-on: ubuntu-latest
    env:
      SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
      SUPABASE_DB_PASSWORD: ${{ github.base_ref == 'main' && secrets.PRODUCTION_DB_PASSWORD || secrets.DEVELOPMENT_DB_PASSWORD }}
      SUPABASE_PROJECT_ID: ${{ github.base_ref == 'main' && secrets.PRODUCTION_PROJECT_ID || secrets.DEVELOPMENT_PROJECT_ID }}
      
    steps:
      - name: Checkout Repository
      - uses: actions/checkout@v4

      - name: Setup Supabase CLI
      - uses: supabase/setup-cli@v1
        with:
          version: latest

      - name: Link Supabase Project
      - run: supabase link --project-ref $SUPABASE_PROJECT_ID
        if: success()

      - name: Push Database Changes 🎉
      - run: supabase db push
